// Comprehensive list of major US cities with state abbreviations.
// Format: "City, ST"
export const US_CITIES: string[] = [
  "New York, NY", "Los Angeles, CA", "Chicago, IL", "Houston, TX", "Phoenix, AZ",
  "Philadelphia, PA", "San Antonio, TX", "San Diego, CA", "Dallas, TX", "San Jose, CA",
  "Austin, TX", "Jacksonville, FL", "Fort Worth, TX", "Columbus, OH", "Charlotte, NC",
  "Indianapolis, IN", "San Francisco, CA", "Seattle, WA", "Denver, CO", "Washington, DC",
  "Nashville, TN", "Oklahoma City, OK", "El Paso, TX", "Boston, MA", "Portland, OR",
  "Las Vegas, NV", "Detroit, MI", "Memphis, TN", "Louisville, KY", "Baltimore, MD",
  "Milwaukee, WI", "Albuquerque, NM", "Tucson, AZ", "Fresno, CA", "Mesa, AZ",
  "Sacramento, CA", "Atlanta, GA", "Kansas City, MO", "Colorado Springs, CO", "Omaha, NE",
  "Raleigh, NC", "Miami, FL", "Long Beach, CA", "Virginia Beach, VA", "Oakland, CA",
  "Minneapolis, MN", "Tulsa, OK", "Arlington, TX", "Tampa, FL", "New Orleans, LA",
  "Wichita, KS", "Cleveland, OH", "Bakersfield, CA", "Aurora, CO", "Anaheim, CA",
  "Honolulu, HI", "Santa Ana, CA", "Riverside, CA", "Corpus Christi, TX", "Lexington, KY",
  "Stockton, CA", "Henderson, NV", "Saint Paul, MN", "St. Louis, MO", "Cincinnati, OH",
  "Pittsburgh, PA", "Greensboro, NC", "Anchorage, AK", "Plano, TX", "Lincoln, NE",
  "Orlando, FL", "Irvine, CA", "Newark, NJ", "Toledo, OH", "Durham, NC",
  "Chula Vista, CA", "Fort Wayne, IN", "Jersey City, NJ", "St. Petersburg, FL", "Laredo, TX",
  "Madison, WI", "Chandler, AZ", "Buffalo, NY", "Lubbock, TX", "Scottsdale, AZ",
  "Reno, NV", "Glendale, AZ", "Gilbert, AZ", "Winston-Salem, NC", "North Las Vegas, NV",
  "Norfolk, VA", "Chesapeake, VA", "Garland, TX", "Irving, TX", "Hialeah, FL",
  "Fremont, CA", "Boise, ID", "Richmond, VA", "Baton Rouge, LA", "Spokane, WA",
  "Des Moines, IA", "Tacoma, WA", "San Bernardino, CA", "Modesto, CA", "Fontana, CA",
  "Santa Clarita, CA", "Birmingham, AL", "Oxnard, CA", "Fayetteville, NC", "Moreno Valley, CA",
  "Rochester, NY", "Glendale, CA", "Huntington Beach, CA", "Salt Lake City, UT", "Grand Rapids, MI",
  "Amarillo, TX", "Yonkers, NY", "Aurora, IL", "Montgomery, AL", "Akron, OH",
  "Little Rock, AR", "Huntsville, AL", "Augusta, GA", "Port St. Lucie, FL", "Grand Prairie, TX",
  "Columbus, GA", "Tallahassee, FL", "Overland Park, KS", "Tempe, AZ", "McKinney, TX",
  "Mobile, AL", "Cape Coral, FL", "Shreveport, LA", "Frisco, TX", "Knoxville, TN",
  "Worcester, MA", "Brownsville, TX", "Vancouver, WA", "Fort Lauderdale, FL", "Sioux Falls, SD",
  "Ontario, CA", "Chattanooga, TN", "Providence, RI", "Newport News, VA", "Rancho Cucamonga, CA",
  "Santa Rosa, CA", "Oceanside, CA", "Salem, OR", "Elk Grove, CA", "Garden Grove, CA",
  "Pembroke Pines, FL", "Eugene, OR", "Corona, CA", "Cary, NC", "Springfield, MO",
  "Fort Collins, CO", "Jackson, MS", "Alexandria, VA", "Hayward, CA", "Lancaster, CA",
  "Lakewood, CO", "Clarksville, TN", "Palmdale, CA", "Salinas, CA", "Springfield, MA",
  "Hollywood, FL", "Pasadena, TX", "Sunnyvale, CA", "Macon, GA", "Pomona, CA",
  "Escondido, CA", "Killeen, TX", "Naperville, IL", "Joliet, IL", "Bellevue, WA",
  "Rockford, IL", "Savannah, GA", "Paterson, NJ", "Torrance, CA", "Bridgeport, CT",
  "McAllen, TX", "Mesquite, TX", "Syracuse, NY", "Midland, TX", "Pasadena, CA",
  "Murfreesboro, TN", "Miramar, FL", "Dayton, OH", "Fullerton, CA", "Olathe, KS",
  "Orange, CA", "Thornton, CO", "Roseville, CA", "Denton, TX", "Waco, TX",
  "Surprise, AZ", "Carrollton, TX", "West Valley City, UT", "Charleston, SC", "Warren, MI",
  "Hampton, VA", "Gainesville, FL", "Visalia, CA", "Coral Springs, FL", "Columbia, SC",
  "Cedar Rapids, IA", "Sterling Heights, MI", "New Haven, CT", "Stamford, CT", "Concord, CA",
  "Kent, WA", "Santa Clara, CA", "Elizabeth, NJ", "Round Rock, TX", "Thousand Oaks, CA",
  "Lafayette, LA", "Athens, GA", "Topeka, KS", "Simi Valley, CA", "Fargo, ND",
  "Norman, OK", "Columbia, MO", "Abilene, TX", "Wilmington, NC", "Hartford, CT",
  "Victorville, CA", "Pearland, TX", "Vallejo, CA", "Ann Arbor, MI", "Berkeley, CA",
  "Allentown, PA", "Richardson, TX", "Odessa, TX", "Arvada, CO", "Cambridge, MA",
  "Sugar Land, TX", "Beaumont, TX", "Lansing, MI", "Evansville, IN", "Rochester, MN",
  "Independence, MO", "Fairfield, CA", "Provo, UT", "Clearwater, FL", "College Station, TX",
  "West Jordan, UT", "Carlsbad, CA", "El Monte, CA", "Murrieta, CA", "Temecula, CA",
  "Springfield, IL", "Palm Bay, FL", "Costa Mesa, CA", "Westminster, CO", "North Charleston, SC",
  "Miami Gardens, FL", "Manchester, NH", "High Point, NC", "Downey, CA", "Clovis, CA",
  "Pompano Beach, FL", "Pueblo, CO", "Elgin, IL", "Lowell, MA", "Antioch, CA",
  "West Palm Beach, FL", "Peoria, IL", "Everett, WA", "Ventura, CA", "Centennial, CO",
  "Lakeland, FL", "Gresham, OR", "Richmond, CA", "Billings, MT", "Inglewood, CA",
  "Broken Arrow, OK", "Sandy Springs, GA", "Jurupa Valley, CA", "Hillsboro, OR", "Waterbury, CT",
  "Santa Maria, CA", "Boulder, CO", "Greeley, CO", "Daly City, CA", "Meridian, ID",
  "Lewisville, TX", "Davie, FL", "West Covina, CA", "League City, TX", "Tyler, TX",
  "Norwalk, CA", "San Mateo, CA", "Green Bay, WI", "Wichita Falls, TX", "Sparks, NV",
  "Lakewood, NJ", "Burbank, CA", "Rialto, CA", "Allen, TX", "El Cajon, CA",
  "Las Cruces, NM", "Renton, WA", "Davenport, IA", "South Bend, IN", "Vista, CA",
  "Edinburg, TX", "Tuscaloosa, AL", "Carmel, IN", "Spokane Valley, WA", "San Angelo, TX",
  "Vacaville, CA", "Clinton, MI", "Bend, OR", "Woodbridge, NJ", "Tustin, CA",
  "Iowa City, IA", "Brockton, MA", "Quincy, MA", "Compton, CA", "Yakima, WA",
  "Lehi, UT", "Bryan, TX", "Edison, NJ", "Bloomington, MN", "Concord, NC",
  "Flint, MI", "Hartford, WI", "Lynn, MA", "Bellingham, WA", "Lakeland, TN",
  "Champaign, IL", "Beaverton, OR", "Trenton, NJ", "Tracy, CA", "Brooklyn Park, MN",
  "San Marcos, CA", "Mountain View, CA", "Sunrise, FL", "Plantation, FL", "New Bedford, MA",
  "Largo, FL", "Sandy, UT", "Roanoke, VA", "Fishers, IN", "Indio, CA",
  "Albany, NY", "Federal Way, WA", "Auburn, WA", "Conroe, TX", "Buckeye, AZ",
  "Westland, MI", "Goodyear, AZ", "Boca Raton, FL", "Schaumburg, IL", "Asheville, NC",
];